# Generated by Django 5.2.9 on 2026-02-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_projects_app', '0002_telecom_totalcharges_alter_avacado_id_alter_bank_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HREmployeePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('DailyRate', models.IntegerField()),
                ('DistanceFromHome', models.IntegerField()),
                ('Education', models.IntegerField()),
                ('EnvironmentSatisfaction', models.IntegerField()),
                ('HourlyRate', models.IntegerField()),
                ('JobInvolvement', models.IntegerField()),
                ('JobLevel', models.IntegerField()),
                ('JobSatisfaction', models.IntegerField()),
                ('MonthlyIncome', models.IntegerField()),
                ('MonthlyRate', models.IntegerField()),
                ('NumCompaniesWorked', models.IntegerField()),
                ('PercentSalaryHike', models.IntegerField()),
                ('PerformanceRating', models.IntegerField()),
                ('RelationshipSatisfaction', models.IntegerField()),
                ('StockOptionLevel', models.IntegerField()),
                ('TotalWorkingYears', models.IntegerField()),
                ('TrainingTimesLastYear', models.IntegerField()),
                ('WorkLifeBalance', models.IntegerField()),
                ('YearsAtCompany', models.IntegerField()),
                ('YearsInCurrentRole', models.IntegerField()),
                ('YearsSinceLastPromotion', models.IntegerField()),
                ('YearsWithCurrManager', models.IntegerField()),
                ('BusinessTravel', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('EducationField', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('JobRole', models.CharField(max_length=50)),
                ('MaritalStatus', models.CharField(max_length=20)),
                ('OverTime', models.CharField(max_length=10)),
                ('prediction', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math_score', models.IntegerField()),
                ('reading_score', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('race_ethnicity', models.CharField(max_length=50)),
                ('parental_level_of_education', models.CharField(max_length=100)),
                ('lunch', models.CharField(max_length=50)),
                ('test_preparation_course', models.CharField(max_length=50)),
                ('prediction', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
